name: l10n updates

on:
  workflow_call:

jobs:
  l10n:
    name: l10n updates
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Push l10n updates
      run: |
        git config --global user.name github-actions
        git config --global user.email github-actions@github.com
        git remote add l10n https://github.com/nvdaaddons/${GITHUB_REPOSITORY#*/}
        git fetch l10n
        git reset l10n/stable addon/doc addon/locale
        git commit -m "Update translations"
        git pull
        git push
